# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-26 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pnt_name', models.CharField(help_text='Имя точки', max_length=30)),
                ('pnt_code', models.CharField(help_text='Код точки', max_length=30)),
                ('pnt_adress', models.CharField(help_text='Адрес точки', max_length=30)),
                ('latitude', models.DecimalField(decimal_places=2, help_text='Широта ', max_digits=5)),
                ('longitude', models.DecimalField(decimal_places=2, help_text='Долгота ', max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Point_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(help_text='Имя типа', max_length=200)),
                ('type_description', models.CharField(help_text='Описание', max_length=200)),
            ],
        ),
    ]
