# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-27 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing_apps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='latitude',
            field=models.DecimalField(decimal_places=2, help_text='Широта', max_digits=5),
        ),
        migrations.AlterField(
            model_name='point',
            name='longitude',
            field=models.DecimalField(decimal_places=2, help_text='Долгота', max_digits=5),
        ),
    ]
